(define (pascal r c)
  (cond ((= r 0) 1)
        ((= c 0) 1)
        ((= c r) 1)
        (else 
          (newline)
          (display "Row: ")
          (display r)
          (newline)
          (display "Column: ")
          (display c)
          (+ (pascal (- r 1) (- c 1)) (pascal (- r 1) c))
          )
        )
  )

(newline)
(display (pascal 2 2))
(newline)
(display (pascal 3 2))
(newline)
(display (pascal 5 3))
(newline)
(display (pascal 4 2))
(newline)
(display (pascal 32 16))
(newline)
