(define steps 0)
(define (count-change amount)
  (cc amount 5))

(define (cc amount kinds-of-change)
  (set! steps (+ steps 1))
  (cond ((= amount 0) 1)
        ((or (< amount 0) (= kinds-of-change 0)) 0)
        (else (+ (cc amount
                     (- kinds-of-change 1))
                 (cc (- amount
                        (first-denomination kinds-of-change))
                     kinds-of-change)))))

(define (first-denomination kinds-of-change)
  (cond ((= kinds-of-change 1) 1)
        ((= kinds-of-change 2) 5)
        ((= kinds-of-change 3) 10)
        ((= kinds-of-change 4) 25)
        ((= kinds-of-change 5) 50)))

(set! steps 0)
(newline)
(display "(count-change 1): ")
(display (count-change 1))
(newline)
(display "Steps: ")
(display steps)
(set! steps 0)
(newline)
(display "(count-change 2): ")
(display (count-change 2))
(newline)
(display "Steps: ")
(display steps)
(set! steps 0)
(newline)
(display "(count-change 3): ")
(display (count-change 3))
(newline)
(display "Steps: ")
(display steps)
(set! steps 0)
(newline)
(display "(count-change 4): ")
(display (count-change 4))
(newline)
(display "Steps: ")
(display steps)
(newline)
(set! steps 0)
(newline)
(display "(count-change 5): ")
(display (count-change 5))
(newline)
(display "Steps: ")
(display steps)
(newline)
(newline)
(set! steps 0)
(newline)
(display "(count-change 6): ")
(display (count-change 6))
(newline)
(display "Steps: ")
(display steps)
(newline)
(newline)
(set! steps 0)
(newline)
(display "(count-change 7): ")
(display (count-change 7))
(newline)
(display "Steps: ")
(display steps)
(newline)
(newline)
(set! steps 0)
(newline)
(display "(count-change 8): ")
(display (count-change 8))
(newline)
(display "Steps: ")
(display steps)
(newline)
(newline)
(set! steps 0)
(newline)
(display "(count-change 9): ")
(display (count-change 9))
(newline)
(display "Steps: ")
(display steps)
(newline)
(newline)
(set! steps 0)
(newline)
(display "(count-change 10): ")
(display (count-change 10))
(newline)
(display "Steps: ")
(display steps)
(newline)
(newline)
(set! steps 0)
(newline)
(display "(count-change 11): ")
(display (count-change 11))
(newline)
(display "Steps: ")
(display steps)
(newline)
(newline)
(set! steps 0)
(newline)
(display "(count-change 12): ")
(display (count-change 12))
(newline)
(display "Steps: ")
(display steps)
(newline)
(newline)
(set! steps 0)
(newline)
(display "(count-change 13): ")
(display (count-change 13))
(newline)
(display "Steps: ")
(display steps)
(newline)
(newline)
(set! steps 0)
(newline)
(display "(count-change 14): ")
(display (count-change 14))
(newline)
(display "Steps: ")
(display steps)
(newline)
(newline)
(set! steps 0)
(newline)
(display "(count-change 15): ")
(display (count-change 15))
(newline)
(display "Steps: ")
(display steps)
(newline)
(newline)
(set! steps 0)
(newline)
(display "(count-change 16): ")
(display (count-change 16))
(newline)
(display "Steps: ")
(display steps)
(newline)
(newline)
(set! steps 0)
(newline)
(display "(count-change 17): ")
(display (count-change 17))
(newline)
(display "Steps: ")
(display steps)
(newline)
(newline)
(set! steps 0)
(newline)
(display "(count-change 18): ")
(display (count-change 18))
(newline)
(display "Steps: ")
(display steps)
(newline)
(newline)
(set! steps 0)
(newline)
(display "(count-change 19): ")
(display (count-change 19))
(newline)
(display "Steps: ")
(display steps)
(newline)
(newline)
(set! steps 0)
(newline)
(display "(count-change 20): ")
(display (count-change 20))
(newline)
(display "Steps: ")
(display steps)
(newline)
(newline)
(set! steps 0)
(newline)
(display "(count-change 21): ")
(display (count-change 21))
(newline)
(display "Steps: ")
(display steps)
(newline)
