(define count 0)
(define halve_count 0)
(define double_count 0)
(define (double a)
  (set! double_count (+ double_count 1))
  (+ a a))

(define (even? n)
  (= (remainder n 2) 0))

(define (halve-iter acc n)
  (cond ((= n 0) acc)
        ((> n 0) (halve-iter (+ acc 1) (- n 2)))
        (else    (halve-iter (- acc 1) (+ n 2)))))

(define (halve a)
  (set! halve_count (+ halve_count 1))
  (halve-iter 0 a))

(define (mult m n)
  (set! count (+ count 1))
  (cond ((= n 0) 0)
        ((even? n) (mult (double m) (halve n)))
        ((> n 0)   (+ m (mult m (- n 1))))
        (else      (- (mult m (+ n 1)) m))))

(newline)
(set! count 0)
(display "(mult 2 2): ")
(display (mult 2 2))
(newline)
(display "Count: ")
(display count)
(newline)
(display "Double count: ")
(display double_count)
(newline)
(display "Halve count: ")
(display halve_count)
(newline)
(set! count 0)
(set! double_count 0)
(set! halve_count 0)
(newline)
(display "(mult 4 4): ")
(display (mult 4 4))
(newline)
(display "Count: ")
(display count)
(newline)
(display "Double count: ")
(display double_count)
(newline)
(display "Halve count: ")
(display halve_count)
(newline)
(set! count 0)
(set! double_count 0)
(set! halve_count 0)
(newline)
(display "(mult 256 4096): ")
(display (mult 256 4096))
(newline)
(display "Count: ")
(display count)
(newline)
(display "Double count: ")
(display double_count)
(newline)
(display "Halve count: ")
(display halve_count)
(newline)
(set! count 0)
(set! double_count 0)
(set! halve_count 0)
(newline)
(display "(mult 11 42): ")
(display (mult 11 42))
(newline)
(display "Count: ")
(display count)
(newline)
(display "Double count: ")
(display double_count)
(newline)
(display "Halve count: ")
(display halve_count)
(newline)
(set! count 0)
(set! double_count 0)
(set! halve_count 0)
(newline)

